default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_39966_development


test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_39966_test


production:
  <<: *default
  adapter: mysql2
  database: furima-39966_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
